# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 06:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('first_name', models.CharField(max_length=350)),
                ('last_name', models.CharField(max_length=350)),
                ('avatar', models.ImageField(blank=True, upload_to=b'', verbose_name='Avatar')),
                ('can_comment', models.BooleanField(default=True, verbose_name='Can comment')),
                ('can_login', models.BooleanField(default=True, verbose_name='Can login')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('address_street', models.CharField(blank=True, default='', max_length=150, verbose_name='Street')),
                ('address_place', models.CharField(blank=True, default='', max_length=150, verbose_name='Place')),
                ('address_postcode', models.CharField(blank=True, default='', max_length=10, verbose_name='Postal code')),
                ('country', models.CharField(blank=True, default='', max_length=100, verbose_name='Country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
