# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
    ]
