# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20160512_2356'),
        ('users', '0002_auto_20160511_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_categories',
            field=models.ManyToManyField(blank=True, to='content.Category', verbose_name='Categories'),
        ),
    ]
